add cd to script dir for sesame

diff --git a/build_tomcat-sesame b/build_tomcat-sesame
--- a/build_tomcat-sesame
+++ b/build_tomcat-sesame
@@ -12,6 +12,7 @@ wget http://sourceforge.net/projects/sesame/files/Sesame%202/2.7.8/openrdf-sesam
 tar -zxvf openrdf-sesame-2.7.8-sdk  || echo "FAILED: rc=$? untar sesame" >&2
 echo "sbin"
 rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/sbin /u/metanet || echo "FAILED: rc=$? rsync sbin" >&2
+cd /u/metanet/sbin
 echo "update scripts"
-sed -i 's_\(^MNDATADIR=\).*_\1/u/metanet/data_' setupnewsesame.sh
-sed -i 's_\(^SESAMEDIR=\).*_\1/u/metanet/tools64/openrdf-sesame-2.7.8-sdk_' setupnewsesame.sh
+sed -i 's_\(^MNDATADIR=\).*_\1/u/metanet/data_' setupnewsesame.sh || echo "FAILED: rc=$? update setupnewsesame1" >&2
+sed -i 's_\(^SESAMEDIR=\).*_\1/u/metanet/tools64/openrdf-sesame-2.7.8-sdk_' setupnewsesame.sh || echo "FAILED: rc=$? update setupnewsesame2" >&2
