git clone metanet etc and source it

diff --git a/build_and_test b/build_and_test
--- a/build_and_test
+++ b/build_and_test
@@ -4,11 +4,16 @@
 # 
 # profile
 # reconcile differences:  metanet.bashrc 
-mv -f .bashrc /home/mnauto/.bashrc || echo "FAILED: rc=$? mv .bashrc " >&2
+#mv -f .bashrc /home/mnauto/.bashrc || echo "FAILED: rc=$? mv .bashrc " >&2
 mkdir /u/metanet/etc
 #mv -f metanet.bashrc.old /u/metanet/etc/metanet.bashrc || echo "FAILED: rc=$? mv .bashrc " >&2
 # >> replace with git clone
-rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/etc/metanet.bashrc  /u/metanet/etc || echo "FAILED: rc=$? rsync metanet.rsync" >&2
+# /u/metanet/git/rdfowl-files.git/
+# git clone ssh://sjdayday@mirto1.icsi.berkeley.edu/u/metanet/git/vm-metanet.git vmbin
+cd /u/metanet/etc
+git clone ssh://sjdayday@mirto1.icsi.berkeley.edu/u/metanet/git/metanet-etc.git/
+#rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/etc/metanet.bashrc  /u/metanet/etc || echo "FAILED: rc=$? rsync metanet.rsync" >&2
+echo "if [ -f /u/metanet/etc/metanet.bashrc ] ; then\n source /u/metanet/etc/metanet.bashrc\nfi" >> /home/mnauto/.bashrc
 source ~/.bashrc
 export PATH=${PATH}:/home/mnauto/vmbin
 #
@@ -45,7 +50,7 @@ build_freeling
 # note:  error checking depends on hard-coded error filename
 #
 echo "Finished building programs." >&2
-ANY_ERROR=$(grep 'FAILED:' /home/metanet/bin/build_err.txt | wc -l)
+ANY_ERROR=$(grep 'FAILED:' /home/mnauto/vmbin/build_err.txt | wc -l)
 #
 # ...copy over needed data
 cd ~/vmbin
