move freeling from tools64 to tools, and change whats excluded from tools64

diff --git a/build_freeling b/build_freeling
--- a/build_freeling
+++ b/build_freeling
@@ -1,10 +1,15 @@
 #!/bin/bash
 #
 # install freeling
-cd /u/metanet/tools64/src
+NOWTIME=$(date +"%Y.%m.%d--%H-%M")
+echo "&NOWTIME freeling"
+cd /u/metanet/tools/src
 wget http://devel.cpl.upc.edu/freeling/downloads/freeling-3.1.tar.gz || echo "FAILED: rc=$? wget freeling" >&2
 tar -zxvf freeling-3.1.tar.gz
-cd /u/metanet/tools64/src/freeling-3.1/
-./configure --prefix=/u/metanet/tools64 || echo "FAILED: rc=$? feeling configure" >&2
+cd /u/metanet/tools/src/freeling-3.1/
+./configure --prefix=/u/metanet/tools || echo "FAILED: rc=$? feeling configure" >&2
 make || echo "FAILED: rc=$? freeling make" >&2
 make install || echo "FAILED: rc=$? freeling make install" >&2
+cd /u/metanet/tools64
+ln -s ../tools/freeling-3.1 freeling-3.1
+echo "&NOWTIME freeling complete"
