load_data:  spa-parsing

diff --git a/load_data b/load_data
--- a/load_data
+++ b/load_data
@@ -29,6 +29,9 @@ rsync -rltqzhe ssh --exclude-from '/home/mnauto/vmbin/exclude-tools64.txt' sjday
 cd /u/metanet/tools
 rsync -rltqzhe ssh  sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/tools/etc /u/metanet/tools || echo "FAILED: rc=$? rsync tools etc" >&2
 NOWTIME=$(date +"%Y.%m.%d--%H-%M")
+echo "$NOWTIME spa-parsing"
+rsync -rltqzhe ssh  sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/tools/spa-parsing /u/metanet/tools || echo "FAILED: rc=$? rsync tools spa-parsing" >&2
+NOWTIME=$(date +"%Y.%m.%d--%H-%M")
 echo "$NOWTIME repository wiktionary"
 rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/repository/wiktionary /u/metanet/repository || echo "FAILED: rc=$? rsync repository wiktionary" >&2
 NOWTIME=$(date +"%Y.%m.%d--%H-%M")
