metanet/tools64 from tools

diff --git a/load_data b/load_data
--- a/load_data
+++ b/load_data
@@ -66,7 +66,7 @@ echo "repository"
 rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/repository /u/metanet || echo "FAILED: rc=$? rsync repository" >&2
 # 10G
 echo "tools"
-rsync -rltqzhe ssh --exclude=virtualenv sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/tools/ /u/metanet/tools || echo "FAILED: rc=$? rsync tools" >&2
+rsync -rltqzhe ssh --exclude=virtualenv sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/tools64/ /u/metanet/tools64 || echo "FAILED: rc=$? rsync tools" >&2
 cd /u/metanet
 mkdir IARPATesting
 echo "IARPATesting"
